export const BK_AGENDA_COLUMNS = () => [
  {
    Header: "No",
    accessor: "number",
    disableFilters: true,
    width: null,
    displayType: "string",
    valueField: "number",
    actionButton: [],
  },
  {
    Header: "Kode Persuratan",
    accessor: "kode_persuratan",
    disableFilters: true,
    width: null,
    displayType: "string",
    valueField: "kode_persuratan",
    actionButton: [],
  },
  {
    Header: "Tanggal Terima/Kirim Surat",
    accessor: "tanggal_terima_kirim_surat",
    disableFilters: true,
    width: null,
    displayType: "string",
    valueField: "tanggal_terima_kirim_surat",
    actionButton: [],
  },
  {
    Header: "Jenis Surat",
    accessor: "jenis_surat",
    disableFilters: true,
    width: null,
    displayType: "toTitleCase",
    valueField: "jenis_surat",
    actionButton: [],
  },
  {
    Header: "Pengirim/Kepada",
    accessor: "pengirim",
    disableFilters: true,
    width: null,
    displayType: "suratMasukPengirim",
    valueField: "",
    actionButton: [],
  },
  {
    Header: "Lampiran",
    accessor: "lampiran",
    disableFilters: true,
    width: null,
    displayType: "lampiranFile",
    valueField: "upload_lampiran_surat",
    actionButton: [],
  },
  {
    Header: "",
    accessor: "action",
    width: "5%",
    disableSortBy: true,
    show: true,
    displayType: "actionButton",
    valueField: "",
    actionButton: ["detail", "update", "delete"],
  },
]
