export const MASTER_DATA_JENIS_KELAMIN_REGEX = /(Laki-Laki|Perempuan)/

export const MASTER_DATA_AGAMA_REGEX =
  /(Islam|Kristen|Katolik|Hindu|Buddha|Konghucu|Kepercayaan Lainnya)/

export const MASTER_DATA_GOLONGAN_DARAH_REGEX =
  /(A|B|AB|O|A\+|B\+|AB\+|O\+|A-|B-|AB-|O-|Tidak Tahu)/

export const MASTER_DATA_GOLONGAN_DARAH_LIST = [
  "A",
  "B",
  "AB",
  "O",
  "A+",
  "B+",
  "AB+",
  "O+",
  "A-",
  "B-",
  "AB-",
  "O-",
  "Tidak Tahu",
]

export const MASTER_DATA_PEKERJAAN_REGEX =
  /(Belum\/Tidak Bekerja|Mengurus Rumah Tangga|Pelajar\/Mahasiswa|Pensiunan|Pewagai Negeri Sipil|Tentara Nasional Indonesia|Kepolisisan RI|Perdagangan|Peternak|Industri|Konstruksi|Transportasi|Karyawan Swasta|Karyawan BUMN|Karyawan BUMD|Karyawan Honorer|Buruh Harian Lepas|Pembantu Rumah Tangga|Tukang Cukur|Tukang Listrik|Tukang Batu|Tukang Kayu|Tukang Sol Sepatu|Tukang Jahit|Tukang Gigi|Penata Rias|Penata Busana|Penata Rambut|Mekanik|Seniman|Tabib|Paraji|Perancang Busana|Penterjemah|Imam Masjid|Pendeta|Pastor|Wartawan|Ustadz\/Mubaligh|Juru Masak|Promotor Acara|Anggota DPR-RI|Anggota DPD|Anggota BPK|Presiden|Anggota Mahkamah Konstitusi|Anggota Kabinet\/Kementerian|Duta Besar|Gubernur|Wakil Gubernur|Bupati|Wakil Bupati|Walikota|Wakil Walikota|Anggota DPRD Kabupaten\/Kota|Dosen|Guru|Pilot|Pengacara|Notaris|Arsitek|Akuntan|Konsultan|Dokter|Bidan|Perawat|Apoteker|Penyiar Televisi|Penyiar Radio|Pelaut|Peneliti|Sopir|Pialang|Paranormal|Pedagang|Perangkat Desa|Kepala Desa|Biarawati|Wiraswasta|Pekerjaan Lainnya)/

export const MASTER_DATA_PENDIDIKAN_LIST = [
  "-",
  "Belum/Tidak Bekerja",
  "Mengurus Rumah Tangga",
  "Pelajar/Mahasiswa",
  "Pensiunan",
  "Pegawai Negeri Sipil",
  "Tentara Nasional Indonesia",
  "Kepolisian RI",
  "Perdagangan",
  "Peternak",
  "Industri",
  "Konstruksi",
  "Transportasi",
  "Karyawan Swasta",
  "Karyawan BUMN",
  "Karyawan BUMD",
  "Karyawan Honorer",
  "Buruh Harian Lepas",
  "Pembantu Rumah Tangga",
  "Tukang Cukur",
  "Tukang Listrik",
  "Tukang Batu",
  "Tukang Kayu",
  "Tukang Sol Sepatu",
  "Tukang Jahit",
  "Tukang Gigi",
  "Penata Rias",
  "Penata Busana",
  "Penata Rambut",
  "Mekanik",
  "Seniman",
  "Tabib",
  "Paraji",
  "Perancang Busana",
  "Penterjemah",
  "Imam Masjid",
  "Pendeta",
  "Pastor",
  "Wartawan",
  "Ustadz/Mubaligh",
  "Juru Masak",
  "Promotor Acara",
  "Anggota DPR-RI",
  "Anggota DPD",
  "Anggota BPK",
  "Presiden",
  "Anggota Mahkamah Konstitusi",
  "Anggota Kabinet/Kementerian",
  "Duta Besar",
  "Gubernur",
  "Wakil Gubernur",
  "Bupati",
  "Wakil Bupati",
  "Walikota",
  "Wakil Walikota",
  "Anggota DPRD Kabupaten/Kota",
  "Dosen",
  "Guru",
  "Pilot",
  "Pengacara",
  "Notaris",
  "Arsitek",
  "Akuntan",
  "Konsultan",
  "Dokter",
  "Bidan",
  "Perawat",
  "Apoteker",
  "Penyiar Televisi",
  "Penyiar Radio",
  "Pelaut",
  "Peneliti",
  "Sopir",
  "Pialang",
  "Paranormal",
  "Pedagang",
  "Perangkat Desa",
  "Kepala Desa",
  "Biarawati",
  "Wiraswasta",
  "Pekerjaan Lainnya",
  "Buruh Pabrik",
  "Buruh Tani",
  "Nelayan/Perikanan",
  "Petani",
  "Petani/Pekebun",
  "TKI",
  "TKW",
  "Pegawai Negeri Sipil",
  "Peternak",
  "Karyawan Honorer",
  "Buruh Harian Lepas",
  "Tukang Cukur",
  "Tukang Listrik",
  "Tukang Batu",
  "Tukang Kayu",
  "Tukang Jahit",
  "Tukang Gigi",
  "Wartawan",
  "Juru Masak",
  "Presiden",
  "Gubernur",
  "Wakil Gubernur",
  "Pilot",
  "Pengacara",
  "Notaris",
  "Akuntan",
  "Apoteker",
  "Pelaut",
  "Peneliti",
  "Sopir",
  "Pialang",
  "Perangkat Desa",
  "Biarawati",
  "Wiraswasta",
  "Buruh Tani",
  "Petani",
]

export const MASTER_DATA_PENDIDIKAN_REGEX =
  /(-|Tidak\/Belum Sekolah|Belum Tamat SD\/Sederajat|Tamat SD\/Sederajat|SLTP\/Sederajat|SLTA\/Sederajat|Diploma I\/II|Diploma III\/Sarjana Muda|Diploma IV\/Strata I|Strata II|Strata III)/

export const MASTER_DATA_KEWARGANEGARAAN_REGEX = /^(WNI|WNA)$/

export const MASTER_DATA_KEDUDUKAN_DALAM_KELUARGA_REGEX =
  /(-|Kepala Keluarga|Suami|Istri|Anak|Menantu|Cucu|Orang Tua|Mertua|Famili Lain|Pembantu|Lainnya)/

export const MASTER_DATA_STATUS_PERKAWINAN_REGEX =
  /(Belum Kawin|Kawin|Cerai Hidup|Cerai Mati|Kawin Tercatat|Kawin Tidak Tercatat)/

export const TANGGAL_REGEX = /^(?:\d{4}-\d{2}-\d{2})?$/
