interface IDataPokokDesa {
  _id: any
  bulan: string
  tahun: Date
  kategori: string
  informasi_desa?: IInformasiDesa
  personil_desa?: IPersonilDesa
  data_umum?: IDataUmum
  keuangan?: IKeuangan
  kelembagaan?: IKelembagaan
}

interface IInformasiDesa {
  kode_desa: string
  nama_desa: string
  kecamatan: string
  kabupaten_kota: string
  provinsi: string
  tahun_pembentukan: number
  dasar_hukum_pembentukan: string
  peta_resmi_wilayah: string
  longitude: number
  latitude: number
  sebelah_utara: string
  sebelah_barat: string
  sebelah_selatan: string
  sebelah_timur: string
}
interface IPersonilDesa {
  nama_kepala_desa: string
  pangkat_kepala_desa: string
  nip_kepala_desa: string
  pendidikan_terakhir_kepala_desa: string
  pelatihan_kepala_desa: string
  jenis_kelamin_kepala_desa: string
  nama_sekretaris_desa: string
  pangkat_sekretaris_desa: string
  nip_sekretaris_desa: string
  pendidikan_terakhir_sekretaris_desa: string
  pelatihan_sekretaris_desa: string
  jenis_kelamin_sekretaris_desa: string
  nama_ketua_bpd: string
  pendidikan_terakhir_ketua_bpd: string
  pelatihan_ketua_bpd: string
  jenis_kelamin_ketua_bpd: string
}
interface IDataUmum {
  tipologi_desa: string
  klasifikasi_desa: string
  kategori_desa: string
  komoditas_unggulan_berdasarkan_luas_tanam: string
  komoditas_unggulan_berdasarkan_nilai_ekonomi: string
  luas_lahan_sawah: number
  luas_lahan_ladang: number
  luas_lahan_perkebunan: number
  luas_lahan_peternakan: number
  luas_hutan: number
  luas_waduk: number
  luas_lahan_lainnya: number
  jumlah_sertifikat_tanah: number
  luas_tanah_memliki_sertifikat_tanah: number
  luas_tanah_kas_desa: number
  jarak_dari_pusat_pemerintahan_kecamatan: number
  jarak_dari_pusat_pemerintahan_kota: number
  jarak_dari_kota_kabupaten: number
  jarak_dari_ibukota_provinsi: number
  keluarga_pra_sejahtera: number
  keluarga_sejahtera_I: number
  keluarga_sejahtera_II: number
  keluarga_sejahtera_III: number
  keluarga_sejahtera_III_plus: number
  jumlah_laki_laki: number
  jumlah_perempuan: number
  jumlah_usia_0_17: number
  jumlah_usia_18_56: number
  jumlah_usia_56_ke_atas: number
  jumlah_karyawan: number
  jumlah_pegawai_negeri_sipil: number
  jumlah_tni_polri: number
  jumlah_pegawai_swasta: number
  jumlah_wiraswasta: number
  jumlah_petani: number
  jumlah_buruh_tani: number
  jumlah_nelayan: number
  jumlah_peternak: number
  jumlah_pekerja_jasa: number
  jumlah_pengrajin: number
  jumlah_pekerja_seni: number
  jumlah_pensiunan: number
  jumlah_pekerja_lainnya: number
  jumlah_penganggur: number
  rasio_murid_guru_tk: number
  rasio_murid_guru_sd: number
  rasio_murid_guru_smp: number
  rasio_murid_guru_sma: number
  rasio_murid_guru_akademi: number
  rasio_murid_guru_sarjana: number
  rasio_murid_guru_pasca_sarjana: number
  rasio_penduduk_dokter_umum: number
  rasio_penduduk_dokter_spesialis: number
  rasio_penduduk_bidan: number
  rasio_penduduk_mantri: number
  rasio_penduduk_perawat: number
  jumlah_lulusan_tk: number
  jumlah_lulusan_sd: number
  jumlah_lulusan_smp: number
  jumlah_lulusan_sma: number
  jumlah_lulusan_akademi: number
  jumlah_lulusan_s1: number
  jumlah_lulusan_s2: number
  jumlah_lulusan_s3: number
  jumlah_lulusan_pondok_pesantren: number
  jumlah_lulusan_pendidikan_agama: number
  jumlah_lulusan_sekolah_luar_biasa: number
  jumlah_kursus_keterampilan: number
  jumlah_tidak_lulus: number
  jumlah_tidak_bersekolah: number
  prasarana_puskesmas: number
  prasarana_puskesmas_pembantu: number
  prasarana_poskesdes: number
  prasarana_posyandu: number
  prasarana_perpustakaan_desa: number
  prasarana_gedung_sekolah_paud: number
  prasarana_gedung_sekolah_tk: number
  prasarana_gedung_sekolah_sd: number
  prasarana_gedung_sekolah_smp: number
  prasarana_gedung_sekolah_sma: number
  prasarana_gedung_perguruan_tinggi: number
  prasarana_masjid: number
  prasarana_mushola: number
  prasarana_gereja: number
  prasarana_pura: number
  prasarana_vihara: number
  prasarana_klenteng: number
  prasarana_olahraga: number
  prasarana_kesenian_budaya: number
  prasarana_balai_pertemuan: number
  prasarana_sumur_desa: number
  prasarana_pasar_desa: number
  prasarana_lainnya: number
  prasarana_jalan_desa: number
  prasarana_jalan_kabupaten: number
  prasarana_jalan_provinsi: number
  prasarana_jalan_nasional: number
  prasarana_tambatan_perahu: number
  prasarana_perahu_motor: number
  prasarana_lapangan_terbang: number
  prasarana_jembatan_besi: number
  prasarana_hidran_umum: number
  prasarana_penampung_air_hujan: number
  prasarana_pamsimas: number
  prasarana_pengolahan_air_bersih: number
  prasarana_sumur_gali: number
  prasarana_sumur_pompa: number
  prasarana_tangki_air: number
  prasarana_mck_umum: number
  prasarana_jamban_keluarga: number
  prasarana_saluran_drainase: number
  prasarana_pintu_air: number
  prasarana_saluran_irigasi: number
}
interface IKeuangan {
  pendapatan_desa: number
  pendapatan_asli_desa: number
  pendapatan_pungutan: number
  pendapatan_hasil_usaha: number
  pendapatan_hibah: number
  pendapatan_lainnya: number
  pendapatan_bantuan_yang_diterima: number
  pendapatan_bantuan_pemerintah: number
  pendapatan_bantuan_provinsi: number
  pendapatan_bantuan_kabupaten: number
  pendapatan_bantuan_lainnya: number
  silpa_sikpa: number
  dana_cadangan: number
  belanja_desa: number
  belanja_rutin_desa: number
  belanja_tidak_rutin_desa: number
}
interface IKelembagaan {
  jumlah_pengurus_lpm: number
  jumlah_anggota_lpm: number
  jumlah_kegiatan_per_bulan_lpm: number
  jumlah_dana_yang_dikelola_lpm: number
  pemangku_adat: number
  kepengurusan_adat: number
  simbol_adat: number
  kegiatan_adat: number
  jumlah_pengurus_pkk: number
  jumlah_anggota_pkk: number
  jumlah_kegiatan_per_bulan_pkk: number
  jumlah_buku_administrasi_yang_dikelola_pkk: number
  jumlah_dana_yang_dikelola_pkk: number
  jumlah_bumdes: number
  jumlah_modal_besar_bumdes: number
  jumlah_keuangan_yang_dikelola_bumdes: number
  jenis_kegiatan_karangtaruna: number
  jumlah_pengurus_karangtaruna: number
  jumlah_anggota_karangtaruna: number
  jumlah_rw: number
  jumlah_rt: number
  jumlah_bantuan_yang_diterima_rw: number
  jumlah_bantuan_yang_diterima_rt: number
  lembaga_kemasyarakatan_lainnya: number
}

export const DataPokokDesaField = {
  _id: "pk",
  bulan: "",
  tahun: 0,
  informasi_desa: {
    kode_desa: "",
    nama_desa: "",
    kecamatan: "",
    kabupaten_kota: "",
    provinsi: "",
    tahun_pembentukan: 0,
    dasar_hukum_pembentukan: "",
    peta_resmi_wilayah: "",
    longitude: 0,
    latitude: 0,
    sebelah_utara: "",
    sebelah_barat: "",
    sebelah_selatan: "",
    sebelah_timur: "",
  },
  personil_desa: {
    nama_kepala_desa: "",
    pangkat_kepala_desa: "",
    nip_kepala_desa: "",
    pendidikan_terakhir_kepala_desa: "",
    pelatihan_kepala_desa: "",
    jenis_kelamin_kepala_desa: "",
    nama_sekretaris_desa: "",
    pangkat_sekretaris_desa: "",
    nip_sekretaris_desa: "",
    pendidikan_terakhir_sekretaris_desa: "",
    pelatihan_sekretaris_desa: "",
    jenis_kelamin_sekretaris_desa: "",
    nama_ketua_bpd: "",
    pendidikan_terakhir_ketua_bpd: "",
    pelatihan_ketua_bpd: "",
    jenis_kelamin_ketua_bpd: "",
  },
  data_umum: {
    tipologi_desa: "",
    klasifikasi_desa: "",
    kategori_desa: "",
    komoditas_unggulan_berdasarkan_luas_tanam: "",
    komoditas_unggulan_berdasarkan_nilai_ekonomi: "",
    luas_lahan_sawah: 0,
    luas_lahan_ladang: 0,
    luas_lahan_perkebunan: 0,
    luas_lahan_peternakan: 0,
    luas_hutan: 0,
    luas_waduk: 0,
    luas_lahan_lainnya: 0,
    jumlah_sertifikat_tanah: 0,
    luas_tanah_memliki_sertifikat_tanah: 0,
    luas_tanah_kas_desa: 0,
    jarak_dari_pusat_pemerintahan_kecamatan: 0,
    jarak_dari_pusat_pemerintahan_kota: 0,
    jarak_dari_kota_kabupaten: 0,
    jarak_dari_ibukota_provinsi: 0,
    keluarga_pra_sejahtera: 0,
    keluarga_sejahtera_I: 0,
    keluarga_sejahtera_II: 0,
    keluarga_sejahtera_III: 0,
    keluarga_sejahtera_III_plus: 0,
    jumlah_laki_laki: 0,
    jumlah_perempuan: 0,
    jumlah_usia_0_17: 0,
    jumlah_usia_18_56: 0,
    jumlah_usia_56_ke_atas: 0,
    jumlah_karyawan: 0,
    jumlah_pegawai_negeri_sipil: 0,
    jumlah_tni_polri: 0,
    jumlah_pegawai_swasta: 0,
    jumlah_wiraswasta: 0,
    jumlah_petani: 0,
    jumlah_buruh_tani: 0,
    jumlah_nelayan: 0,
    jumlah_peternak: 0,
    jumlah_pekerja_jasa: 0,
    jumlah_pengrajin: 0,
    jumlah_pekerja_seni: 0,
    jumlah_pensiunan: 0,
    jumlah_pekerja_lainnya: 0,
    jumlah_penganggur: 0,
    rasio_murid_guru_tk: 0,
    rasio_murid_guru_sd: 0,
    rasio_murid_guru_smp: 0,
    rasio_murid_guru_sma: 0,
    rasio_murid_guru_akademi: 0,
    rasio_murid_guru_sarjana: 0,
    rasio_murid_guru_pasca_sarjana: 0,
    rasio_penduduk_dokter_umum: 0,
    rasio_penduduk_dokter_spesialis: 0,
    rasio_penduduk_bidan: 0,
    rasio_penduduk_mantri: 0,
    rasio_penduduk_perawat: 0,
    jumlah_lulusan_tk: 0,
    jumlah_lulusan_sd: 0,
    jumlah_lulusan_smp: 0,
    jumlah_lulusan_sma: 0,
    jumlah_lulusan_akademi: 0,
    jumlah_lulusan_s1: 0,
    jumlah_lulusan_s2: 0,
    jumlah_lulusan_s3: 0,
    jumlah_lulusan_pondok_pesantren: 0,
    jumlah_lulusan_pendidikan_agama: 0,
    jumlah_lulusan_sekolah_luar_biasa: 0,
    jumlah_kursus_keterampilan: 0,
    jumlah_tidak_lulus: 0,
    jumlah_tidak_bersekolah: 0,
    prasarana_puskesmas: 0,
    prasarana_puskesmas_pembantu: 0,
    prasarana_poskesdes: 0,
    prasarana_posyandu: 0,
    prasarana_perpustakaan_desa: 0,
    prasarana_gedung_sekolah_paud: 0,
    prasarana_gedung_sekolah_tk: 0,
    prasarana_gedung_sekolah_sd: 0,
    prasarana_gedung_sekolah_smp: 0,
    prasarana_gedung_sekolah_sma: 0,
    prasarana_gedung_perguruan_tinggi: 0,
    prasarana_masjid: 0,
    prasarana_mushola: 0,
    prasarana_gereja: 0,
    prasarana_pura: 0,
    prasarana_vihara: 0,
    prasarana_klenteng: 0,
    prasarana_olahraga: 0,
    prasarana_kesenian_budaya: 0,
    prasarana_balai_pertemuan: 0,
    prasarana_sumur_desa: 0,
    prasarana_pasar_desa: 0,
    prasarana_lainnya: 0,
    prasarana_jalan_desa: 0,
    prasarana_jalan_kabupaten: 0,
    prasarana_jalan_provinsi: 0,
    prasarana_jalan_nasional: 0,
    prasarana_tambatan_perahu: 0,
    prasarana_perahu_motor: 0,
    prasarana_lapangan_terbang: 0,
    prasarana_jembatan_besi: 0,
    prasarana_hidran_umum: 0,
    prasarana_penampung_air_hujan: 0,
    prasarana_pamsimas: 0,
    prasarana_pengolahan_air_bersih: 0,
    prasarana_sumur_gali: 0,
    prasarana_sumur_pompa: 0,
    prasarana_tangki_air: 0,
    prasarana_mck_umum: 0,
    prasarana_jamban_keluarga: 0,
    prasarana_saluran_drainase: 0,
    prasarana_pintu_air: 0,
    prasarana_saluran_irigasi: 0,
  },
  keuangan: {
    pendapatan_desa: 0,
    pendapatan_asli_desa: 0,
    pendapatan_pungutan: 0,
    pendapatan_hasil_usaha: 0,
    pendapatan_hibah: 0,
    pendapatan_lainnya: 0,
    pendapatan_bantuan_yang_diterima: 0,
    pendapatan_bantuan_pemerintah: 0,
    pendapatan_bantuan_provinsi: 0,
    pendapatan_bantuan_kabupaten: 0,
    pendapatan_bantuan_lainnya: 0,
    silpa_sikpa: 0,
    dana_cadangan: 0,
    belanja_desa: 0,
    belanja_rutin_desa: 0,
    belanja_tidak_rutin_desa: 0,
  },
  kelembagaan: {
    jumlah_pengurus_lpm: 0,
    jumlah_anggota_lpm: 0,
    jumlah_kegiatan_per_bulan_lpm: 0,
    jumlah_dana_yang_dikelola_lpm: 0,
    pemangku_adat: 0,
    kepengurusan_adat: 0,
    simbol_adat: 0,
    kegiatan_adat: 0,
    jumlah_pengurus_pkk: 0,
    jumlah_anggota_pkk: 0,
    jumlah_kegiatan_per_bulan_pkk: 0,
    jumlah_buku_administrasi_yang_dikelola_pkk: 0,
    jumlah_dana_yang_dikelola_pkk: 0,
    jumlah_bumdes: 0,
    jumlah_modal_besar_bumdes: 0,
    jumlah_keuangan_yang_dikelola_bumdes: 0,
    jenis_kegiatan_karangtaruna: 0,
    jumlah_pengurus_karangtaruna: 0,
    jumlah_anggota_karangtaruna: 0,
    jumlah_rw: 0,
    jumlah_rt: 0,
    jumlah_bantuan_yang_diterima_rw: 0,
    jumlah_bantuan_yang_diterima_rt: 0,
    lembaga_kemasyarakatan_lainnya: 0,
  },
}

export type { IDataPokokDesa }
